# Generated by Django 3.2.16 on 2022-12-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_drinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
