# Generated by Django 3.2.16 on 2022-12-01 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dishes_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dishes',
            new_name='Dish',
        ),
        migrations.RenameModel(
            old_name='Drinks',
            new_name='Drink',
        ),
    ]
