# Generated by Django 3.2.16 on 2022-12-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20221201_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='allergy_icon',
            field=models.CharField(choices=[('none', 'none'), ('cereal', 'cereal'), ('gluten', 'gluten'), ('milk', 'milk'), ('eggs', 'eggs'), ('peanuts', 'peanuts'), ('nuts', 'nuts'), ('crustaceans', 'crustaceans'), ('mustard', 'mustard'), ('fish', 'fish'), ('lupin', 'lupin'), ('sesame', 'sesame'), ('celery', 'celery'), ('soya', 'soya'), ('molluscs', 'molluscs')], default='0', max_length=12),
        ),
    ]
