# Generated by Django 3.2.16 on 2022-11-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_reservation_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='num_of_guest',
        ),
    ]
