# Generated by Django 3.2.16 on 2022-11-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_reservation_num_of_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='num_of_guest',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', 3), ('4', 4), ('5', 5)], default='2'),
        ),
    ]
