# Generated by Django 3.2.16 on 2022-11-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reservation_num_of_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='num_of_guest',
            field=models.IntegerField(),
        ),
    ]
