# Generated by Django 3.2.16 on 2022-11-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_reservation_num_of_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='title',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
