# Generated by Django 3.2.16 on 2022-11-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_reservation_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='num_of_guest',
            field=models.IntegerField(max_length=10),
        ),
    ]
