# Generated by Django 3.2.16 on 2022-11-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_auto_20221130_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='num_of_guest',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='2', max_length=6),
        ),
    ]
