# Generated by Django 3.2.16 on 2022-11-30 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_alter_reservation_num_of_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_table', to='reservation.table', to_field='Name'),
        ),
    ]
