# Generated by Django 3.2.16 on 2022-11-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_alter_reservation_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='title',
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='jala.ksjk@gmail.com', max_length=80),
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='jalal', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone_num',
            field=models.CharField(default='+46789524356', max_length=12),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='num_of_guest',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='2', max_length=6),
        ),
        migrations.AlterField(
            model_name='table',
            name='max_num_guest',
            field=models.PositiveIntegerField(),
        ),
    ]
