# Generated by Django 3.2.16 on 2022-11-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0017_auto_20221130_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date_picked']},
        ),
    ]
