# Generated by Django 3.2.16 on 2022-12-01 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0020_alter_reservation_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['Name']},
        ),
    ]
